language: sh

before_script:
  - sudo add-apt-repository "deb http://archive.ubuntu.com/ubuntu/ trusty-backports restricted main universe"
  - sudo apt-get update -qq
  - sudo apt-get install -qq shellcheck

script:
  - shellcheck functions.sh
  - shellcheck createDirectoriesTree.sh
  - shellcheck common.sh
  - shellcheck Ubuntu/properties.sh
  - shellcheck OS\ X/properties.sh
  - shellcheck install.sh