language: sh

before_script:
  - sudo add-apt-repository "deb http://archive.ubuntu.com/ubuntu/ trusty-backports restricted main universe"
  - sudo apt-get update -qq
  - sudo apt-get install -qq shellcheck

script:
  - shellcheck functions.sh
  - shellcheck createDirectoriesTree.sh
  - shellcheck common.sh
  - shellcheck install.sh
  - shellcheck modules/sdkman/sdkman.sh
  - shellcheck modules/android.sh
  - shellcheck modules/git.sh
  - shellcheck modules/go.sh
  - shellcheck modules/google-drive.sh
  - shellcheck modules/homebrew.sh
  - shellcheck modules/java.sh
  - shellcheck modules/nodejs.sh
  - shellcheck modules/oh-my-zsh.sh

notifications:
  email:
    on_failure: change